### ISSUE TITLE
Ligand escaping from its binding site and moving freely away from protein

### ISSUE THREAD

**Issue by Marwa-Abdelkader** [tubiana/protocolGromacs#1]
First I'd like to thank you for this script, it saved me lots of time and made things easier :).
It just happened that I tried using this script to repeat one simulation I previously have done 2 independent replicas, so I applied some  simple modifications to fit my previous parameters, and it was running smoothly without errors. and I used my mdp files not the ones provided here to keep everything the same in those 2 new replicas. 

In the previous simulation which I did manually before finding this automated script I followed the following method in editing the system topology (topol.top) file:

Before solvation step:

1)Cut [ atomtypes ] section from ligand.itp file, save the file and then paste it under
; Include forcefield parameters
2) Include ligand topology in topol.top file after the position restraint as follows:
; Include ligand topology
#include “ligand.itp”
3) Add in the [ molecules ] section in topol.top :
ligand 1

Then after creating index for ligand and generating position restraint file for ligand after EM:

4)Include posre_ligand.itp in topol.top file after ligand topology and before water topology as follows:
; Ligand position restraints
#ifdef POSRES
#include “posre_ligand.itp”
#endif

The problem is that after the 1st replica using this modified script finished (which was a 500 ns run), I found that the ligand escaped the binding site and was moving freely away from the protein. I'm not sure if the problem came from changing the method I was adapting in adding the ligand position restraint file, or from not adding other needed parameters in the mdp files (which I don't know what exactly should they be?), or is there other reasons that I don't know?

I'm attaching the modified script I used, and my npt.mdp files
[lig_posre_files.zip](https://github.com/tubiana/protocolGromacs/files/7611559/lig_posre_files.zip)

**Comment by tubiana** [comment]
Sorry for the late answer, I guess your problem should be solved here. 
It's a little hard to say if the issue is coming from the ligand parameters, the simulation itself or the input coordinates. 
When doing simulations it's important to check regularly the trajectories, to see if everything is going well. You ligand problem could be due wrong input coordinates (position transformation during preparation) or just the ligand leave the pocket during the simulation and you can't do anything because it's the simulation result itself ;-)
