### ISSUE TITLE
which it better in minimizing in GROMACS a low Max force or a low potential energy?

### ISSUE THREAD

**Issue by hima111997** [tubiana/protocolGromacs#2]
Greeting sir,

thank you for these scripts.

I started minimizing a solvated protein-ligand structure with emtol = 1000 then I tried to reduce the tolerance until I reached 100 and it achieved a maximum force of 99.9 with a potential energy of -927980 but when I tried to make emtol = 50 it said that it could not reach this value and saved coordinates with max force = 321 and a potential energy = -929472
so which is better a low max force or a low potential energy structure?

Thanks

**Comment by tubiana** [comment]
I'm very sorry for my late answer. 

I leave the answer for someone that could be interested as well. 
emtol is one of the criteria to stop the minimization. When applied Fmax < emtol then the minimization stop. But 50kcal/mol-1 is a very low force, and I doubt that it can be reach (or under very specific circumstances). 
Nevertheless, it's not always a good idea to have a very low energetic structure since you still need a bit of energy for the system to evolve. If you are stuck in a energetic well it will be hard to get out of it.

Some people like to minimize for a lot of step and use a very low emtol to ensure that all minimization steps are used, while some other prefer to leave a bit more of energy. And of course the minimization algorithm will also change how much force you applied on each steps :)

Best,
Thibault.
