### ISSUE TITLE
Why there is three replicated required?

### ISSUE THREAD

**Issue by vmevada102** [tubiana/protocolGromacs#5]
It is bit confusing, In this protocol three replicates are generated. 

Can you explain why three replicated required ?

**Comment by Marwa-Abdelkader** [comment]
Some researchers and articles reviewers require that a simulation be replicated 3 times as a sort of validation and sampling a wider space of conformations.

**Comment by tubiana** [comment]
Thank you for answering @Marwa-Abdelkader, and same as the other issue, I just forgot to answer. 
+1 On your answer. 
Reproducibility is important. For example, I already asked to remove an MD result in a paper I reviewed because they show a loss of secondary structure when increasing the temperature slightly. Still, without replicas, it is hard to say if it is because of the temperature or just "by chance". If you observe the same thing in 3 replicas then it is easier to conclude that this observation is due to the parameter you have changed (here: the temperature) and not due to the seed.
