### ISSUE TITLE
How to create the index file in accordance with this protocol?

### ISSUE THREAD

**Issue by vmevada102** [tubiana/protocolGromacs#6]
This protocol is excellent to the new bees like me.

However, I need little more support.
I would like to run the MMPBSA after this run.
For that, it is required to add index file.

Kindly guide to generate this file during this protocol run for Protein-ligand complex.

**Comment by tubiana** [comment]
Hi! 

To generate an index file you need to use `gmx make_ndx`. You can have an usage example on my script here : https://github.com/tubiana/protocolGromacs/blob/a1665af4b6e37a142fd316c8b1b3aa54a33a8fac/runGromacs.sh#L132 

I cannot help you more on your issue since I lack a bit of details and I never used MMGBSA with gromacs so I'm not sure what input you need.

Best regards,
Thibault.
